### ISSUE TITLE
Service not starting on boot

### ISSUE THREAD

**Issue by AndreasVoellmy** [lmammino/cube-daemons#2]
I installed some updates on my Ubuntu VM and now the cube-collector and cube-evaluator don't seem to start up on boot anymore. 

After boot, I do

```
~$ service cube-collector status
cube-collector not running.
```

Strange, since the pid file exists

```
$ cat /var/run/cube/collector.pid 
946
```

and /var/log/boot.log contains

```
...
Starting cube-collector...
Starting cube-evaluator
...
```

If I manually start it:

```
$ sudo service cube-collector start
Starting cube-collector...
```

It starts fine:

```
$ service cube-collector status
cube-collector running.
```

Info about my machine:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.4 LTS"
$ uname -a
Linux maple-vm 3.5.0-49-generic #73~precise1-Ubuntu SMP Wed Apr 2 18:35:12 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Any idea of what may be going wrong here or how to debug this?

**Comment by lmammino** [comment]
Sorry for the late reply @AndreasVoellmy. I've been pretty busy this week.
Anyway I have to admit I'm not a great expert with linux an system V init scripts.

Did your server has been shut down correctly on the previous execution?

I would like to try to make the init scripts LSB compatible (this should improve shut down and startup process and may fix potential problems).

**Comment by lmammino** [comment]
I just updated the init scripts. @AndreasVoellmy, try this new version and let me know, it worked for me on ubuntu quantal.
